# Generated by Django 2.0 on 2018-01-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=20)),
                ('isDone', models.BooleanField()),
                ('createdAt', models.DateTimeField()),
                ('doneAt', models.DateTimeField()),
            ],
        ),
    ]
