# Generated by Django 2.0 on 2018-01-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.AutoField(primary_key=True, serialize=True),
        ),
    ]
