# Generated by Django 2.0 on 2018-01-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskAPI', '0004_auto_20180101_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
